#cloud-config
package_update: true
package_upgrade: true
packages:
  - postgresql
  - postgresql-contrib
runcmd:
  - sudo -u postgres psql -c "CREATE DATABASE order_system_db;"
  - sudo -u postgres psql -c "CREATE USER dbuser WITH ENCRYPTED PASSWORD 'pass123';"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE order_system_db TO dbuser;"
  - sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/*/main/postgresql.conf
  - echo "host all all 10.0.0.0/24 md5" | sudo tee -a /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql
  - sudo ufw allow 5432/tcp
  - sudo ufw --force enable
