#cloud-config
package_update: true
package_upgrade: true
packages:
  - openjdk-17-jdk
  - maven
  - git
  - curl
  - npm
runcmd:
  - git clone https://github.com/Panos994/Order-Dashboard-System.git
  - cd Order-Dashboard-System && mvn spring-boot:run &
  # Εναλλακτικά, build και run jar αν θέλεις
  # - cd Order-Dashboard-System && mvn package && java -jar target/*.jar &
  # Προσάρμοσε PORT αν χρειάζεται
  - cd Order-Dashboard-System/order_system_frontend && npm install && npm run serve &
  - sudo ufw allow 80/tcp
  - sudo ufw allow 8080/tcp
  - sudo ufw --force enable
